//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : A.java
//  @ Date : 5/18/2019
//  @ Author : 
//
//



package pppp;


public abstract class A {
	public abstract void fun();
	public void hh() {
	
	}
}
