//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : B.java
//  @ Date : 5/18/2019
//  @ Author : 
//
//



package pppp;


public abstract class B extends A {
	public void fun() {
	
	}
	
	public void fun() {
	
	}
}
