//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pppp.java
//  @ Date : 5/18/2019
//  @ Author : 
//
//



package pppp;


public class Pppp {
	public void fun() {
	
	}
	
	public static void main(String[] args) {
	
	}
}
